exercise-5-2
liferay/liferay-course-client-extensions pull request #3
Opened 2024-10-31 17:09 UTC by davicms

2024-10-31 20:20 UTC, smbmatheus-lr requested changes
Hi @davicms , please fix the naming in the .yaml file. 
Thanks.

2024-10-31 20:20 UTC, smbmatheus-lr commented on client-extensions/liferay-clarity-global-css-2/client-extension.yaml
> +liferay-sample-global-css:
Please fix the Client Extension name.

2024-10-31 20:20 UTC, smbmatheus-lr commented on client-extensions/liferay-clarity-global-css-2/client-extension.yaml
> +    name: Liferay Sample Global CSS 2
Fix CX name

2024-12-11 15:43 UTC, dnebing commented
@davicms the name in the client-extension.yaml file still doesn't match the folder name, still has 'sample' instead of 'clarity'.

2024-12-12 12:43 UTC, closed without merging